# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21cc2280386119fe87f336b4c555ebb4f2660e692de4fb22e58c7d119ab5dca2a1d28c9568c8416f1d7609e47f467a98728f11f69d09f36ae2f2756e97a23264

test:
  secret_key_base: 9d6f94533d918ea67c60441633e85f28da2617810f5c29c1e62e9f4993cac470b68056eac2f6d65d250b235f4f6bdfcd5edddc8feda94485e97956f0cf7ea9dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
